### ISSUE TITLE
feat req: devcontainer

### ISSUE THREAD

**Issue by jarrodcolburn** [redking00/vscode-nbts#1]
.devcontainer/template would be great (for Codespaces and local via cli and docker)

This seems like it'd be a perfect use case for .devcontainer so people could quickly jump in.

The normal Jupyter Notebook devcontainer template at https://github.com/github/codespaces-jupyter

Especially as VS Code extensions can be specified in the `customizations.vscode.extensions`

**Comment by jarrodcolburn** [comment]
A good start for `.devconatiner` might be the following. Commented out changed from Codespaces-jupyter original
```json5
{
  "image": "mcr.microsoft.com/devcontainers/universal:2",
  "hostRequirements": {
    "cpus": 4
  },
  "waitFor": "onCreateCommand",
  // "updateContentCommand": "python3 -m pip install -r requirements.txt",
  "updateContentCommand": "curl -fsSLO https://deno.land/install.sh && sh ./install.sh -y",
  "postCreateCommand": "",
  "customizations": {
    "codespaces": {
      "openFiles": []
    },
    "vscode": {
      "extensions": [
       // "ms-toolsai.jupyter",
       // "ms-python.python"
       "redking00.vscode-nbts"
      ]
    }
  }
}
```

**Comment by redking00** [comment]
Done!

Thanks for the idea, @jarrodcolburn. I think it works
