### ISSUE TITLE
Duplicate IntelliSense Suggestions in VSCode

### ISSUE THREAD

**Issue by Hazi7** [redking00/vscode-nbts#10]
The VSCode IntelliSense suggestions are appearing twice, seemingly provided by both `done` and `vscode`. 

And when I reload VSCode, it initially appears to be using Deno as the LSP server correctly, but after a while, it switches to vscode-typescript, as most types become any.

I attempted to configure the settings as provided in your codespace, but the issue persists.

```json
"typescript.validate.enable": false
```

### Steps to Reproduce

1. Create a `*.nb.ts` file
2. Start coding

### Expected Behavior

The suggestions should not appear duplicate.

### Screenshots

![image](https://github.com/user-attachments/assets/05039def-5964-4175-96b1-e6afb95b88a8)
![image](https://github.com/user-attachments/assets/febc56a8-5f65-489f-ac76-b7d6cfc4b585)

### Versions

* VSCode: 1.96.0
* Extension: 1.0.18

**Comment by redking00** [comment]
Hi @Hazi7! 
Thank you for taking your time to report this issue. 

My LSP is a layer on top of the original Deno LSP. The problem could originate from it ([see](https://github.com/denoland/vscode_deno/issues/1202)), so I would need some details:

 - What version of Deno are you using?

- Did you run the command "Deno: Initialize workspace configuration"?

- Could you give a concrete code example?

Thx!

**Comment by Hazi7** [comment]
> Hi @Hazi7! Thank you for taking your time to report this issue.
> 
> My LSP is a layer on top of the original Deno LSP. The problem could originate from it ([see](https://github.com/denoland/vscode_deno/issues/1202)), so I would need some details:
> 
> * What version of Deno are you using?
> * Did you run the command "Deno: Initialize workspace configuration"?
> * Could you give a concrete code example?
> 
> Thx!

Hi @redking00 !

- this is my deno detail：
![image](https://github.com/user-attachments/assets/41b46f99-bf2d-4f2b-be94-4d9362a6ad4a)

- i have init deno workspace
![image](https://github.com/user-attachments/assets/70aa99bd-cadc-4d47-87d7-75fc29eba3a7)

- 我使用original Deno LSP的时候没有出现建议重复出现的情况，但是会有跨单元格提示报错的情况，你的这个lsp解决了它，所以我切换到了你的这个lsp。

我上传了我的工作区到github上：
https://github.com/Hazi7/deno-demo

**Comment by Hazi7** [comment]
> Hi @Hazi7! Thank you for taking your time to report this issue.
> 
> My LSP is a layer on top of the original Deno LSP. The problem could originate from it ([see](https://github.com/denoland/vscode_deno/issues/1202)), so I would need some details:
> 
> * What version of Deno are you using?
> * Did you run the command "Deno: Initialize workspace configuration"?
> * Could you give a concrete code example?
> 
> Thx!

Hi @redking00,

Thank you for taking the time to look into this issue. I'm using the following Deno version:
![image](https://github.com/user-attachments/assets/41b46f99-bf2d-4f2b-be94-4d9362a6ad4a)

I have run the command "Deno: Initialize workspace configuration" as shown here:
![image](https://github.com/user-attachments/assets/70aa99bd-cadc-4d47-87d7-75fc29eba3a7)

When I used the original Deno LSP, I didn't encounter the issue of repeated suggestions, but I did experience cross-cell error prompts. However, your LSP resolved this issue, which is why I switched to it.

I have uploaded my workspace to GitHub for your reference: https://github.com/Hazi7/deno-demo

Thank you!

**Comment by Hazi7** [comment]
I disabled this built-in extension in my workspace and everything is back to normal.

![image](https://github.com/user-attachments/assets/d395b4c6-43e7-46ac-b4ab-c3114de6034e)

**Comment by redking00** [comment]
@Hazi7,

There was a problem with the build process. I think it is solved and now the extension behaves better. The "typescript.validation.enabled" option is no longer necessary. In fact it is counterproductive now.
There is no need to disable the typescript builtin extension
Can you try it? [v.1.0.19](https://github.com/redking00/vscode-nbts/releases/tag/v1.0.19)
