### ISSUE TITLE
devcontianer as templage

### ISSUE THREAD

**Issue by jarrodcolburn** [redking00/vscode-nbts#2]
when comparing this repo's devcontianer to official [jupyter notebook](https://github.com/github/codespaces-jupyter), I notice I'm not getting the option to spin it up using template 

ref jupyter repo...
![image](https://github.com/user-attachments/assets/d8bb9332-0cc4-4155-b148-d288c0022c33)

I think this is something that has to be done in settings, based on.... https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

**Comment by redking00** [comment]
@jarrodcolburn [vscode-nbts-codespaces](https://github.com/redking00/vscode-nbts-codespaces)
