### ISSUE TITLE
Suport non-standard mime from Deno.jupyter.display

### ISSUE THREAD

**Issue by janckerchen** [redking00/vscode-nbts#6]
**Describe the bug**

When encountering objects with non-standard mime, the returned data structure from lsp does not appear to be a standard jupyter, and the non-standard mime data is collapsed into the `other` field.   

**To Reproduce**

1. first step

set breakpoint at session.ts:210

2. second step

test.nb.ts

```ts
await Deno.jupyter.display(
    {
        "x-application/github-issues": JSON.stringify({a:1}),
        "x-application/github-issues2": JSON.stringify({a:1}),
    },
    {raw:true}
)
```

3. third step

check data at breakpoint, Non-standard mime data is collapsed into the `other` field, and there's only one, lost `x-application/github-issues2` .

<img width="674" alt="image" src="https://github.com/user-attachments/assets/773da0a0-8724-48e1-a58e-97deb473d6b1">

**Expected behavior**

 should cover this situation.  

I don't understand if this is the standard way of jupter, or the unique way of deno's lsp, and don't understand why it returns so?

**Comment by redking00** [comment]
@janckerchen Thanks for the report. 
That code is kernel controller's business. Is not an lsp issue. Just released a new version. Can you take a look?

**Comment by janckerchen** [comment]
fixed. However, the x-application/github-issues renderer internally handles the conversion of strings to json objects, so you can just branch else.

<img width="548" alt="image" src="https://github.com/user-attachments/assets/56309e96-2c3b-450b-8f60-01a59b1e2ed9">

I need to change launch.json after every pull to use F5 debug

<img width="444" alt="image" src="https://github.com/user-attachments/assets/2fbfb424-f11d-4eba-b3cb-85a3831119c6">

**Comment by redking00** [comment]
@janckerchen ready now https://github.com/redking00/vscode-nbts/commit/f427a6c47ca1032c91b05cfc9327a1fce71cbd96?

**Comment by janckerchen** [comment]
fixed, great job
